package common

// 订单状态
const (
	// 待处理订单
	HAMSTER_TRIPLE_GAME_ORDER_STATUS_NEW = 0
	// 已采集订单
	HAMSTER_TRIPLE_GAME_ORDER_STATUS_PENDING = 1
	// 已结算订单
	HAMSTER_TRIPLE_GAME_ORDER_STATUS_SETTLE = 2
	// 订单出现异常
	HAMSTER_TRIPLE_GAME_ORDER_STATUS_ERROR = 3
)
